"""Concatenate every migration into one file that rebuilds the database.

    python scripts/build-db-rebuild.py

Writes supabase/REBUILD_ALL.sql. Run it after adding a migration, and commit
the result, so that standing the database up again is always one paste rather
than twenty-six.

WHY THIS EXISTS

The Supabase project was removed while the subscription was lapsed, taking the
schema with it. The migrations were all that was left, and they turned out to
be enough: nothing had ever been created by hand in the dashboard, including
the `logos` storage bucket, which migration 0001 inserts. But applying them one
at a time through the SQL editor is twenty-six chances to skip one or run two
out of order, and the failure is silent until some feature breaks weeks later.

The checks below are the point as much as the concatenation is. They refuse to
write the file if the migrations would not survive a clean run:

  - a migration that references a table a LATER migration creates
  - a create that is not guarded, so a second run would fail half way

Both were verified true of the set as it stands. If either ever stops being
true, this fails loudly here rather than at 2am in a SQL editor.
"""

import datetime
import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MIGRATIONS = os.path.join(ROOT, "supabase", "migrations")
TARGET = os.path.join(ROOT, "supabase", "REBUILD_ALL.sql")


def strip_comments(sql: str) -> str:
    sql = re.sub(r"--[^\n]*", "", sql)
    return re.sub(r"/\*.*?\*/", "", sql, flags=re.S)


def check(files: list[str]) -> list[str]:
    """Return a list of reasons the set would not survive a clean run."""
    problems: list[str] = []
    order = {f: i for i, f in enumerate(files)}

    # Which migration creates each table.
    creates: dict[str, int] = {}
    for f in files:
        sql = strip_comments(open(f, encoding="utf-8").read())
        for m in re.finditer(
            r"create\s+table\s+(?:if\s+not\s+exists\s+)?(?:public\.)?([a-z0-9_]+)", sql, re.I
        ):
            creates.setdefault(m.group(1).lower(), order[f])

    for f in files:
        sql = strip_comments(open(f, encoding="utf-8").read())
        i = order[f]
        name = os.path.basename(f)

        # A foreign key or ALTER against a table that does not exist yet.
        for pattern, label in ((r"references\s+(?:public\.)?([a-z0-9_]+)", "references"),
                               (r"alter\s+table\s+(?:if\s+exists\s+)?(?:public\.)?([a-z0-9_]+)",
                                "alters")):
            for m in re.finditer(pattern, sql, re.I):
                t = m.group(1).lower()
                if t in creates and creates[t] > i:
                    problems.append(
                        f"{name} {label} `{t}`, which is only created later in "
                        f"{os.path.basename(files[creates[t]])}"
                    )

        # Anything that would fail on a second run.
        tables = len(re.findall(r"create\s+table", sql, re.I))
        guarded = len(re.findall(r"create\s+table\s+if\s+not\s+exists", sql, re.I))
        if tables != guarded:
            problems.append(f"{name} has {tables - guarded} `create table` without `if not exists`")

        policies = len(re.findall(r"create\s+policy", sql, re.I))
        dropped = len(re.findall(r"drop\s+policy\s+if\s+exists", sql, re.I))
        if policies > dropped:
            problems.append(
                f"{name} creates {policies} policies but only drops {dropped} first, "
                "so a second run fails"
            )

    return problems


HEADER = """-- =====================================================================
-- AI-BOS: REBUILD THE WHOLE DATABASE, IN ONE PASTE
-- =====================================================================
--
-- Generated by scripts/build-db-rebuild.py on {today}.
-- DO NOT EDIT THIS FILE. Edit the migrations and run the script again.
--
-- WHAT THIS IS FOR
--
-- The Supabase project this app used was removed, so the schema had to be
-- stood up again from nothing. Running {n} migration files by hand, in order,
-- through the SQL editor is {n} chances to skip one. This is all of them,
-- concatenated in order, so it is one paste.
--
-- HOW TO RUN IT
--
--   1. Supabase dashboard -> your project -> SQL Editor -> New query
--   2. Paste this entire file
--   3. Run
--
-- It is SAFE TO RUN TWICE. Every create is guarded (`if not exists`, or a
-- `drop ... if exists` immediately before), and the generator refuses to
-- write this file if that ever stops being true.
--
-- WHAT IT DOES NOT DO
--
--   - It does not bring back any DATA. Tables come back empty.
--   - It does not bring back USER ACCOUNTS. Those live in Supabase's own
--     `auth` schema, which this cannot write. Everyone signs up again.
--   - It does not set any environment variable. See docs/RESTORE.md.
--
-- =====================================================================

"""


def main() -> None:
    files = sorted(glob.glob(os.path.join(MIGRATIONS, "*.sql")))
    if not files:
        raise SystemExit(f"no migrations found in {MIGRATIONS}")

    problems = check(files)
    if problems:
        print("The migrations would not survive a clean run:\n", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        raise SystemExit("\nnothing written; fix the migrations first")

    parts = [HEADER.format(today=datetime.date.today(), n=len(files))]
    for f in files:
        body = open(f, encoding="utf-8").read().strip()
        parts.append(
            "\n-- ---------------------------------------------------------------------\n"
            f"-- {os.path.basename(f)}\n"
            "-- ---------------------------------------------------------------------\n\n"
            + body
            + ("" if body.endswith(";") else ";")
            + "\n\n"
        )
    parts.append("-- ===================== end of rebuild =====================\n")

    with open(TARGET, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("".join(parts))

    kb = os.path.getsize(TARGET) // 1024
    print(f"checked {len(files)} migrations: no forward references, every create guarded")
    print(f"wrote supabase/REBUILD_ALL.sql  ({kb}KB)")


if __name__ == "__main__":
    main()
